### ISSUE TITLE
Zalando Releases repo is not public

### ISSUE THREAD

**Issue by mostlymagic** [zalando/test-service-kit#1]
resolvers += "Zalando Releases" at "https://maven.zalando.net/content/groups/public/content/repositories/releases"

This makes this library unusable for anybody outside Zalando.
Please deploy this library to a public repo (Maven Central?)

**Comment by hjacobs** [comment]
:+1: see https://github.com/zalando/zalando-howto-open-source#official-repositories

**Comment by Unisay** [comment]
@mostlymagic @hjacobs Thanks guys, will do.

**Comment by Unisay** [comment]
https://issues.sonatype.org/browse/OSSRH-20440

**Comment by Unisay** [comment]
@hjacobs  Sonatype asks someone who already has deployer access to this groupId comment here and confirm that I should also receive access. Could you please comment here https://issues.sonatype.org/browse/OSSRH-20440?

**Comment by hjacobs** [comment]
@Unisay done.

**Comment by Unisay** [comment]
Published to maven central repo via Sonatype
